Add a warning to `Delimiter::None` that rustc currently does not respect it.
dtolnay/proc-macro2 pull request #455
Opened 2024-04-25 14:32 UTC by CensoredUsername

Currently when used to implement a proc_macro, `Delimiter::None` simply doesn't do what it is documented to do.

While this is a rustc bug (rust-lang/rust#67062), it is a long standing one, and hard to discover.
This pull request adds a warning to inform users of this issue, with a link to the relevant issue, and a version number of the last known affected rustc version.

2024-04-25 14:49 UTC, dtolnay requested changes
Could you please add this in proc_macro's documentation to begin with? Then we can mirror it here. I am not interested in the documentation being out of sync.

2024-04-25 15:19 UTC, CensoredUsername commented
Of course. I wasn't aware that it was a mirror of that.

I'll follow up here if/when that's done.

2024-05-25 09:51 UTC, CensoredUsername commented
This is now a port of the accepted rust-lang/rust/pull/124389

2024-05-25 17:46 UTC, dtolnay approved these changes
Thank you!

2024-05-25 17:47 UTC, merged